#!/usr/bin/env python3
##
## EPITECH PROJECT, 2020
## B-MAT-400-LYN-4-1-206neutrinos-clement.fleur [WSL: Debian]
## File description:
## 203
##

import sys
import math

def printHelp():
    print("USAGE\n    ./206neutrinos n a h sd\n\nDESCRIPTION")
    print("    n\t    number of values")
    print("    a\t    arithmetic mean")
    print("    h\t    harmonic mean")
    print("    sd\t   standard deviation")
    sys.exit(0)

def errorHandling():
    i = 1

    if (len(sys.argv) <= 1 or len(sys.argv) > 5):
        print(len(sys.argv))
        print("Error : Please check your arguments.")
        sys.exit(84)
    if sys.argv[1] == "-h":
        printHelp()
    try:
        while (i < len(sys.argv)):
            if (int(sys.argv[i]) < 0):
                sys.exit(84)
            i += 1
    except:
        sys.exit(84)

def main():
    errorHandling()
    terminal = ""
    while (terminal != "END"):
        terminal = input()
        print(terminal)


if __name__ == "__main__":
    main()