##
## EPITECH PROJECT, 2020
## B-CNA-410-LYN-4-1-groundhog-clement.fleur
## File description:
## Makefile
##

SRC		=	src/

NAME	=	groundhog

$(NAME)	:
			cp ./$(SRC)main.py .
			mv main.py groundhog
			chmod +x groundhog

all		:	$(NAME)

clean:
		rm -rf groundhog

fclean:	clean

re	:	fclean all