name: CI c++

on: push
jobs:
  run-tests:
    runs-on: ubuntu-latest

    # needed for criterion
    container:
        image: epitechcontent/epitest-docker:latest

    steps:
    - uses: actions/checkout@v2
    - name: compile binary
      run: |
          make -j
          make re
          make fclean
#  code-quality:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2

#    - name: install dependencies
#      run: |
#          sudo apt install -y clang-tidy
#    - name: clang-format lint
#      run: make CI
