##
## EPITECH PROJECT, 2020
## Desktop [WSL: Debian]
## File description:
## Makefile
##

NAME	=	autoCompletion

$(NAME)	:
			cp main.py autoCompletion
			chmod +x autoCompletion

all		:	$(NAME)

clean:
		rm -rf autoCompletion

fclean:	clean

re	:	fclean all