#!/usr/bin/env python3
##
## EPITECH PROJECT, 2020
## B-MAT-400-LYN-4-1-205IQ-arthur1.perrot
## File description:
## 205IQ
##

import sys
import math
from utils import Gaussian

def help():
    print("USAGE")
    print("\t./205IQ u s [IQ1] [IQ2]\n")
    print("DESCRIPTION")
    print("\tu mean")
    print("\ts standard deviation")
    print("\tIQ1 minimum IQ")
    print("\tIQ2 maximum IQ")
    exit(0)

def errorHandling():
    try:
        if int(sys.argv[1]) < 0 or int(sys.argv[1]) > 200:
            sys.exit(84)
    except:
        sys.exit(84)

def main():
    if (len(sys.argv) == 2 and sys.argv[1] == "-h"):
        help()
    elif len(sys.argv) > 2 and len(sys.argv) < 6:
        errorHandling()
        IQ = Gaussian()
        IQ.init()
    else:
        exit(84)


if __name__ == '__main__':
    main()
